### ISSUE TITLE
KeyError: 'run_id'

### ISSUE THREAD

**Issue by jsalbin1** [grosenberger/easypqp#102]
I am running EasyPQP 0.1.39 in FragPipe 20.0, which has been consistently failing with KeyError: 'run_id'. I have attached the log file from FragPipe. I have not had this issue previously when running 0.1.37. Is there something new in 0.1.39 that might be leading to this error, or something else that I should adjust in my setup?
[log_2023-08-13_05-41-18.txt](https://github.com/grosenberger/easypqp/files/12329215/log_2023-08-13_05-41-18.txt)

**Comment by grosenberger** [comment]
Hi, thanks for reporting this issue. I tried to replicate the problem with EasyPQP 0.1.39 and FragPipe 20.0, but it worked on my system and configuration. Would it be possible to post a minimum example dataset where this failed so I can try to recreate the issue?

Best regards,
George

**Comment by jsalbin1** [comment]
Where can I upload the mzML and FASTA?

**Comment by fcyu** [comment]
It should have been fixed by https://github.com/grosenberger/easypqp/pull/105/commits/400f63a5b46a9478cd45acaad5caac72d5260545, and included in the latest release.

Best,

Fengchao

**Comment by grosenberger** [comment]
Thanks @fcyu!
