### ISSUE TITLE
Issue with EasyPQP 0.1.39

### ISSUE THREAD

**Issue by JesusCastano01** [grosenberger/easypqp#104]
Hi,
I recently ran into some issues when trying to use DIA_spec_lib when using the latest EasyPQP version available (0.1.39 ). I ran similar files uisng Python 3.11 before, and it had worked, so I don't think that is the Python version causing this problem, but this version of EasyPQP.
I'd appreciate any advice on this.
Thanks,
[log_2023-08-17_17-53-26.txt](https://github.com/grosenberger/easypqp/files/12373867/log_2023-08-17_17-53-26.txt)

**Comment by grosenberger** [comment]
Hi, thanks for reporting this issue. I tried to replicate the problem with EasyPQP 0.1.39 and FragPipe 20.0, but it worked on my system and configuration. Would it be possible to post a minimum example dataset where this failed so I can try to recreate the issue?

Best regards,
George
