### ISSUE TITLE
Could you please release version 0.1.41

### ISSUE THREAD

**Issue by fcyu** [grosenberger/easypqp#108]
Hi @grosenberger ,

I was trying to release a new version by pushing a commit (https://github.com/grosenberger/easypqp/commit/f1c6a7d878ea53e231545fd3c62e3e660cbf31b6) and a new tag (0.1.41). But it seems that I need your help to put the new version to PyPI. Could you please release it for us? Or if you tell me how to do that, I can push the new version to PyPI by myself.

Thanks,

Fengchao

**Comment by fcyu** [comment]
I see that you have released the new version. 

Thank you!

Fengchao

**Comment by grosenberger** [comment]
Hi @fcyu ,

I just created a new release on GitHub, which will automatically trigger upload to PyPI. Do you have access rights to do that as well?

Best regards,
George

**Comment by fcyu** [comment]
Oh, I didn't know that after creating a new release, it will automatically trigger the uploading. Then, I will do it by myself next time.

Best,

Fengchao
