### ISSUE TITLE
idXML support

### ISSUE THREAD

**Issue by prvst** [grosenberger/easypqp#112]
Hello, I can see in the code that the convert method can handle idXML, but I can't find the option for it in the commands. Can the idXML format still be used?

**Comment by jonasscheid** [comment]
I would also love to see idXML support again. Looks like, support was not included in the optimizations [between version 0.1.37 and 0.1.38](https://github.com/grosenberger/easypqp/compare/0.1.37...0.1.38).

I guess a new click command `easypqp convertidxml` needs to be written that calls the `parse_idxml` function in the `convert` subpackage, or `easypqp convert` [should allow also idxml parsing](https://github.com/grosenberger/easypqp/blob/e09206120fac425c03442efb0077ff2baa91e1b8/easypqp/main.py#L69) (again)

**Comment by jonasscheid** [comment]
Would love to see it as well. [The CLI flag](https://github.com/grosenberger/easypqp/blob/e09206120fac425c03442efb0077ff2baa91e1b8/easypqp/main.py#L69) doesn't check for idxml anymore. If that is added the idXML is parsed. But it needs to be more robust. I see meta values in there that are not always present leading to crashes
