### ISSUE TITLE
ascii decode problem

### ISSUE THREAD

**Issue by simpsonetti** [grosenberger/easypqp#114]
Hi, fresh ubuntu24.04 lts install for fragpipe with virtualenv. 
I get this: 
UnicodeDecodeError: 'asii' codec can't decode byte 0xc3 in position 106: ordinal not in range(128) decoding with 'ANSI_X3.4-1968' codec failed

I installed easypqp fresh via github. 
Some hints to solve this?
Regards Sebastian

**Comment by guoci** [comment]
@simpsonetti Please show the full log.

**Comment by guoci** [comment]
no response
