### ISSUE TITLE
no decoy in library

### ISSUE THREAD

**Issue by zhutiansheng** [grosenberger/easypqp#32]
I used fragpipe to build library, but there was none decoy in library.tsv and easypqp_lib_openswath.tsv. And the header of these two library were different from tsv format of pqp (http://openswath.org/en/latest/docs/pqp.html). I am puzzled. How to use these two library to run openswath2.4 ?

**Comment by grosenberger** [comment]
After EasyPQP, you need to process the library TSV files by the tools OpenSwathAssayGenerator and OpenSwathDecoyGenerator. If EasyPQP generates ``library.tsv``, this will be the input for ``OpenSwathAssayGenerator -in library.tsv -out library.pqp``.
