### ISSUE TITLE
MSFragger SL Generation

### ISSUE THREAD

**Issue by xLinkKnight** [grosenberger/easypqp#35]
We're attempting to generate a spectral library which is compatible with OpenMS workflows (diaPASEF). We used the easyPQP method bundled in FragPipe to generate a SL from DDA-PASEF timsTOF runs which were spiked with iRT peptides (database included iRT sequences).

The task outputs three files, library.tsv, easypqp_lib_openswath.tsv, and irt.tsv. I haven't had issues converting the .tsv files to .pqp, and I've managed to include decoys as suggested. My question has to do with the correct generation of the iRT library. The OpenSWATH routine requests an iRT library, and I'm not sure how this file get generated. To my knowledge, the MSFragger library files don't include iRT data. I'm sure this is user error, as I'm still attempting to wrap my head around these various operations.

**Comment by grosenberger** [comment]
We typically use EasyPQP with DIA-ps and DDA spectra to generate hybrid libraries. EasyPQP then generates DIA-run matched iRT files that we can directly use in OpenSWATH.

If you generate a library from only DDA files, there are several ways to use internal or external standards, e.g. iRT or ciRT libraries. ``easypqp library --rt_reference`` provides the option to specify such a file.

If your DDA runs closely resemble the DIA runs, a good alternative might also be to just use the full (or potentially downsampled) target library as iRT library. ``OpenSwathWorkflow`` has an option to exclude outlier iRT peptides automatically and will only use those producing a decent signal.
