### ISSUE TITLE
can easypqp build library with irt

### ISSUE THREAD

**Issue by lifeinfo** [grosenberger/easypqp#37]
I built library using fragpipe. And I check the psm.tsv,protein.tsv, interact* files including "iRT" protein. But the final library library.tsv didn't have iRT in side. And , protein like "opl|OPL_HBB-G57A|P68871-G57A" also did not find in library.tsv.
[temp.zip](https://github.com/grosenberger/easypqp/files/5529878/temp.zip)

**Comment by grosenberger** [comment]
By default EasyPQP uses only proteotypic (non-shared) peptides. You can disable this using ``easypqp library --no-proteotypic``.

**Comment by lifeinfo** [comment]
Sorry, I think "iRT" or protein ID like "opl|OPL_HBB-G57A|P68871-G57A" have nothing to do with proteotypic peptides. Moreover, all the 11 iRT peptides are proteotypic peptides.

**Comment by grosenberger** [comment]
Could you please specify the parameters that you used for easypqp? It might be that one of the filters was active and removed the peptides or proteins.

**Comment by lifeinfo** [comment]
In fact, I used fragpipe command 'python -u ../fragpipe13/tools/speclib/gen_con_spec_lib.py $fastaPath ./ $mzxmlfiles $output True unused use_easypqp ciRT 7 "--rt_lowess_fraction 0.01"'

**Comment by lifeinfo** [comment]
@grosenberger

**Comment by grosenberger** [comment]
Is there a way to make FragPipe report the full used EasyPQP command? If not, i would recommend to also ask the FragPipe team about the issue, as the problem could be both on the EasyPQP or FragPipe side.

**Comment by lifeinfo** [comment]
@grosenberger The  generated two *.peaks.tsv were not empty, it seems regular. But the easypqp_lib_openswath.tsv was empty

_______________________full used EasyPQP command________________
/home/biodocker/anaconda3/bin/easypqp convert --pepxml /mnt/data/yuanchunhui2/interact-QE1_181018_OPL0000_TCPA_Prostate_A10.pep.xml --spectra /mnt/data/yuanchunhui2/mzXML/QE1_181018_OPL0000_TCPA_Prostate_A10.mzXML --exclude-range -1.5,3.5 --psms QE1_181018_OPL0000_TCPA_Prostate_A10.psmpkl --peaks QE1_181018_OPL0000_TCPA_Prostate_A10.peakpkl
/home/biodocker/anaconda3/bin/easypqp convert --pepxml /mnt/data/yuanchunhui2/interact-QE1_181018_OPL0000_TCPA_Prostate_B2.pep.xml --spectra /mnt/data/yuanchunhui2/mzXML/QE1_181018_OPL0000_TCPA_Prostate_B2.mzXML --exclude-range -1.5,3.5 --psms QE1_181018_OPL0000_TCPA_Prostate_B2.psmpkl --peaks QE1_181018_OPL0000_TCPA_Prostate_B2.peakpkl
/home/biodocker/anaconda3/bin/easypqp library --psmtsv /mnt/data/yuanchunhui2/psm.tsv --peptidetsv /mnt/data/yuanchunhui2/peptide.tsv --rt_reference /mnt/data/yuanchunhui2/output/irt.tsv --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.01 /mnt/data/yuanchunhui2/output/QE1_181018_OPL0000_TCPA_Prostate_A10.psmpkl /mnt/data/yuanchunhui2/output/QE1_181018_OPL0000_TCPA_Prostate_B2.psmpkl /mnt/data/yuanchunhui2/output/QE1_181018_OPL0000_TCPA_Prostate_A10.peakpkl /mnt/data/yuanchunhui2/output/QE1_181018_OPL0000_TCPA_Prostate_B2.peakpkl

**Comment by lifeinfo** [comment]
[output.zip](https://github.com/grosenberger/easypqp/files/5633636/output.zip)

**Comment by lifeinfo** [comment]
[output.zip](https://github.com/grosenberger/easypqp/files/5633645/output.zip)

**Comment by lifeinfo** [comment]
[input.zip](https://github.com/grosenberger/easypqp/files/5633650/input.zip)

**Comment by lifeinfo** [comment]
Hi, @grosenberger , how are things going? We are still waiting.

**Comment by grosenberger** [comment]
It might be that the missing gene names in your libraries were an issue. I just pushed a patch to the ``master`` branch. Could you please check if that resolves the issue?

``pip install git+https://github.com/grosenberger/easypqp.git@master``

**Comment by lifeinfo** [comment]
@grosenberger. It still dosen't work.

**Comment by grosenberger** [comment]
Well, can you provide a bit more feedback? Using your data and the command

```
easypqp library --psmtsv psm.tsv --peptidetsv peptide.tsv --rt_reference irt.tsv --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.01 QE1_181018_OPL0000_TCPA_Prostate_A10.psmpkl QE1_181018_OPL0000_TCPA_Prostate_B2.psmpkl QE1_181018_OPL0000_TCPA_Prostate_A10.peakpkl QE1_181018_OPL0000_TCPA_Prostate_B2.peakpkl
```

now resulted in a file ``easypqp_lib_openswath.tsv`` containing the iRT transitions. Do you get the same result?

[easypqp_lib_openswath.txt](https://github.com/grosenberger/easypqp/files/5651617/easypqp_lib_openswath.txt)

**Comment by lifeinfo** [comment]
`(base) biodocker@9f2deb7eb6ff:/mnt/data/yuanchunhui2/output$ pip install git+https://github.com/grosenberger/easypqp.git@master
Collecting git+https://github.com/grosenberger/easypqp.git@master
  Cloning https://github.com/grosenberger/easypqp.git (to revision master) to /tmp/pip-req-build-34x16xv7
  Running command git clone -q https://github.com/grosenberger/easypqp.git /tmp/pip-req-build-34x16xv7
Requirement already satisfied (use --upgrade to upgrade): easypqp==0.1.8 from git+https://github.com/grosenberger/easypqp.git@master in /home/biodocker/anaconda3/lib/python3.7/site-packages
Requirement already satisfied: Click in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (7.0)
Requirement already satisfied: numpy in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (1.18.1)
Requirement already satisfied: scipy in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (1.4.1)
Requirement already satisfied: scikit-learn in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (0.22.1)
Requirement already satisfied: statsmodels in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (0.11.0)
Requirement already satisfied: pandas in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (1.0.1)
Requirement already satisfied: biopython in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (1.77)
Requirement already satisfied: pyopenms in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (2.5.0)
Requirement already satisfied: matplotlib in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (3.1.3)
Requirement already satisfied: seaborn in /home/biodocker/anaconda3/lib/python3.7/site-packages (from easypqp==0.1.8) (0.10.0)
Requirement already satisfied: joblib>=0.11 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from scikit-learn->easypqp==0.1.8) (0.14.1)
Requirement already satisfied: patsy>=0.5 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from statsmodels->easypqp==0.1.8) (0.5.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from pandas->easypqp==0.1.8) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from pandas->easypqp==0.1.8) (2019.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from matplotlib->easypqp==0.1.8) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from matplotlib->easypqp==0.1.8) (2.4.6)
Requirement already satisfied: cycler>=0.10 in /home/biodocker/anaconda3/lib/python3.7/site-packages (from matplotlib->easypqp==0.1.8) (0.10.0)
Requirement already satisfied: six in /home/biodocker/anaconda3/lib/python3.7/site-packages (from patsy>=0.5->statsmodels->easypqp==0.1.8) (1.14.0)
Requirement already satisfied: setuptools in /home/biodocker/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->easypqp==0.1.8) (45.2.0.post20200210)
Building wheels for collected packages: easypqp
  Building wheel for easypqp (setup.py) ... done
  Created wheel for easypqp: filename=easypqp-0.1.8-py2.py3-none-any.whl size=200351 sha256=745823221a8520021eb5caca30c477b415cb59e1b70fa5449899cf89e5f2653b
  Stored in directory: /tmp/pip-ephem-wheel-cache-8yqo2x5l/wheels/cf/c6/96/a98c562ffca9b3190b1a1d94d7f59e9d96eec91d91967bef62
Successfully built easypqp
(base) biodocker@9f2deb7eb6ff:/mnt/data/yuanchunhui2/output$ easypqp library --psmtsv psm.tsv --peptidetsv peptide.tsv --rt_reference irt.tsv --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.01 QE1_181018_OPL0000_TCPA_Prostate_A10.psmpkl QE1_181018_OPL0000_TCPA_Prostate_B2.psmpkl QE1_181018_OPL0000_TCPA_Prostate_A10.peakpkl QE1_181018_OPL0000_TCPA_Prostate_B2.peakpkl
Info: There are psm.tsv and peptide.tsv. Will ignore --psm_fdr_threshold, --peptide_fdr_threshold, --protein_fdr_threshold, --pi0_lambda, --proteotypic, and --no-proteotypic.
Info: Reading file QE1_181018_OPL0000_TCPA_Prostate_A10.psmpkl.
Info: Reading file QE1_181018_OPL0000_TCPA_Prostate_B2.psmpkl.
Info: 58 redundant PSMs identified after filtering with psm.tsv and peptide.tsv
Info: easypqp_rt_alignment_QE1_181018_OPL0000_TCPA_Prostate_A10; Peptide overlap between run and reference: 9.
Info: easypqp_rt_alignment_QE1_181018_OPL0000_TCPA_Prostate_B2; Peptide overlap between run and reference: 8.
Info: Parsing file QE1_181018_OPL0000_TCPA_Prostate_A10.peakpkl.
Info: Parsing file QE1_181018_OPL0000_TCPA_Prostate_B2.peakpkl.
Info: Library successfully generated.
(base) biodocker@9f2deb7eb6ff:/mnt/data/yuanchunhui2/output$ 
`
 easypqp_lib_openswath.tsv is still empty.

**Comment by grosenberger** [comment]
I'm not sure if easypqp was successfully installed on your system. Maybe you can try ``pip install --force git+https://github.com/grosenberger/easypqp.git@master`` to ensure that the latest version will be used.

**Comment by lifeinfo** [comment]
Thanks, this solved the problem.
