### ISSUE TITLE
iRT alignment issue

### ISSUE THREAD

**Issue by aparnasrini03** [grosenberger/easypqp#40]
I'm having an issue with aligning some of the files I am using in the easypqp library generation. I have used an iRT reference file with the appropriate format. Most of the runs look like they have good alignment from the plots, but two of them are totally off (I'm getting normalized retention values on the order of e+16). When i manually checked for the iRT peptides in these runs, and performed a basci linear regression, it seemed like a good fit. This is the warning i'm getting when I run easypqp library on only the two files that are giving me this issue, although the output file is still successfully generated. 
eg. 
```bash
easypqp library --rt_reference=$irt --out=$library --peptide_fdr_threshold=$peptide_fdr_threshold \
--protein_fdr_threshold=0.01 --psm_fdr_threshold=0.01 \
--rt_lowess_fraction=0.1 --pi0_lambda=$pi0lambda --peptide_plot=$peptide_plot \
--protein_plot=$protein_plot $inputpsms $inputpeaks
```

```python
Info: easypqp_rt_alignment_filename; Peptide overlap between run and reference: 56.
/home/asrini/ENV/lib/python3.6/site-packages/statsmodels/nonparametric/smoothers_lowess.py:165: RuntimeWarning: invalid value encountered in true_divide
  res = _lowess(y, x, frac=frac, it=it, delta=delta)
/home/asrini/ENV/lib/python3.6/site-packages/statsmodels/nonparametric/smoothers_lowess.py:165: RuntimeWarning: invalid value encountered in greater_equal
  res = _lowess(y, x, frac=frac, it=it, delta=delta)

Info: Library successfully generated.
```

Have tried to debug this issue but ran into some other issues along the way. Thanks for your help! Let me know if you need additional info.

**Comment by grosenberger** [comment]
One option would be to increase ``--rt_lowess_fraction``, does that resolve the issue? As alternative, could you please provide an example dataset, so I can reproduce the issue?

**Comment by aparnasrini03** [comment]
Yes, increasing the --rt_lowess_fraction fixed the issue. Thank again!
