### ISSUE TITLE
retention time reversed 

### ISSUE THREAD

**Issue by zhutiansheng** [grosenberger/easypqp#42]
I ran the following command in linux
`/home/biodocker/anaconda3/bin/easypqp convert --pepxml /mnt/data/fragpipeWorkspace/interact-C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.pep.xml --spectra /mnt/data/fragpipeWorkspace/mzXML/C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.mzXML --exclude-range -1.5,3.5 --psms C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.psmpkl --peaks C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.peakpkl`

I found the retention time of peptides SMAGNIIPAIATTNAVIAGLIVLEGLK and LSITGTYDLK were reversed the order in *run_peaks.tsv and pep.xml. May I know why this happend? Thanks
[temp.zip](https://github.com/grosenberger/easypqp/files/5713289/temp.zip)
The link to mzXML file: https://westlakeu-my.sharepoint.com/:u:/g/personal/zhutiansheng_westlake_edu_cn/EZ5-T93kTdxNjT8IJCASWeIBG_LrFcqbPsXnb1YHlQZncw?e=LVlKgl

**Comment by lifeinfo** [comment]
@grosenberger

**Comment by grosenberger** [comment]
How did you do retention time calibration? Did you use a reference RT coordinates file or did you combine several files together?

**Comment by grosenberger** [comment]
My best guess is that the order of two or more reference RT peptides, either from the run with most identifications or the RT coordinates files are in reverse order between this specific run and the reference.

**Comment by lifeinfo** [comment]
We got the input file of easypqp with *pep.xml file which generated by fragpipe. pep.xml was produced from a single raw file and this step none RT calibration was done I think.

**Comment by grosenberger** [comment]
This is done in the ``easypqp library`` step. For example, running this step without RT reference file results linear scaling from 0-100: ``easypqp convert --pepxml interact-C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.pep.xml --spectra C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.mzXML --exclude-range -1.5,3.5 --psms C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.psmpkl --peaks C20180824sunyt_shaoyk_DDA_MXM_CMZ_M4.peakpkl``

However, in your file, it seems that you conducted non-linear RT alignment against a reference.

Following up on your example, LSITGTYDLK has 4 high confidence PSMs ranging from 3297.780s to 8729.350s, whereas SMAGNIIPAIATTNAVIAGLIVLEGLK has an RT of 7649.340s. Depending on whether you computed consensus (median RT) or best replicate spectra (highest probability), the order of this peptide will be reversed.

**Comment by lifeinfo** [comment]
Thanks, this may be caused by combine several files together
