### ISSUE TITLE
Is there any way to filter ions in the library conforming to the down criterions like spectrast2tsv?

### ISSUE THREAD

**Issue by lifeinfo** [grosenberger/easypqp#44]
I used following command to build the library:
python -u ../fragpipe13/tools/speclib/gen_con_spec_lib.py $fastaPath ./ ${mzfiles:1} $output True unused use_easypqp c iRT 7 "--rt_lowess_fraction 0.01" 
Is there any way to filter ions in the library conforming to the down criterions like spectrast2tsv?

Lower and upper mass limits of fragment ions
remove transitions with Q3 falling in the swath mass range when provided the swath/dia window.
Fragment ion charge states allowed.
Could you please check and fix this issue?

Thanks,

**Comment by grosenberger** [comment]
Yes, but this is not part of EasyPQP, but rather implemented in ``OpenSwathAssayGenerator``. Please refer to the options available with ``OpenSwathAssayGenerator --helphelp``.
