### ISSUE TITLE
There are errors in running EasyPQP

### ISSUE THREAD

**Issue by xuezhangzhi** [grosenberger/easypqp#50]
We find  an error from EasyPQP when we use it :
![image](https://user-images.githubusercontent.com/68281140/110054272-c72ac480-7d95-11eb-97ad-7861982ab869.png)
we check the log of error file and find the error message below :
![image](https://user-images.githubusercontent.com/68281140/110054451-13760480-7d96-11eb-94ea-c18acdc04caf.png)
Can you take a look when you have time?

**Comment by guoci** [comment]
@xuezhangzhi please post the `.pep.xml` file

**Comment by xuezhangzhi** [comment]
> @xuezhangzhi please post the `.pep.xml` file
Here are two error files，I added the TXT suffix

[interact-A20180408YueL_PCT_plasma25_DDA1__repB.pep.xml.txt](https://github.com/grosenberger/easypqp/files/6135910/interact-A20180408YueL_PCT_plasma25_DDA1__repB.pep.xml.txt)
[interact-A20180408YueL_PCT_plasma25_DDA2__repA.pep.xml.txt](https://github.com/grosenberger/easypqp/files/6135911/interact-A20180408YueL_PCT_plasma25_DDA2__repA.pep.xml.txt)

**Comment by guoci** [comment]
@xuezhangzhi what was used to generate the `pep.xml` files? It doesn't look like PeptideProphet generated. 
@grosenberger can you take a look at this? I think you might be familiar with that part of the code.

**Comment by grosenberger** [comment]
Were your pepXML processed by PeptideProphet (and optionally iProphet)? It doesn't look like there are any scores in there except the raw search engine scores.

**Comment by xuezhangzhi** [comment]
Pep.xml files are generated by peptideProphet, and here is the command file :
[pipeline .sh.txt](https://github.com/grosenberger/easypqp/files/6201529/pipeline.sh.txt)
I added the TXT suffix

**Comment by xuezhangzhi** [comment]
@guoci @grosenberger
