### ISSUE TITLE
easyPQP(0.1.9) cannot be installed in Fragpipe(version 15)

### ISSUE THREAD

**Issue by lyumengge** [grosenberger/easypqp#51]
![error](https://user-images.githubusercontent.com/80483932/110841736-401fa400-82e1-11eb-8772-7176ee8d8a51.png)

**Comment by guoci** [comment]
@lyumengge Your screenshot is unreadable

**Comment by lyumengge** [comment]
![image](https://user-images.githubusercontent.com/80483932/110843247-051e7000-82e3-11eb-98e7-1120b8cf1ef1.png)

Fragpipe 15 GUI cannot update easyPQP, here is the warning message:

C:\Users\admin>python -m pip install -e git+https://github.com/grosenberger/easypqp.git@master#egg=SomeProject
Obtaining SomeProject from git+https://github.com/grosenberger/easypqp.git@master#egg=SomeProject
  Cloning https://github.com/grosenberger/easypqp.git (to revision master) to c:\users\admin\src\someproject
  Running command git clone -q https://github.com/grosenberger/easypqp.git 'C:\Users\admin\src\someproject'
  fatal: unable to access 'https://github.com/grosenberger/easypqp.git/': OpenSSL SSL_read: Connection was reset, errno 10054
WARNING: Discarding git+https://github.com/grosenberger/easypqp.git@master#egg=SomeProject. Command errored out with exit status 128: git clone -q https://github.com/grosenberger/easypqp.git 'C:\Users\admin\src\someproject' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement someproject (unavailable)
ERROR: No matching distribution found for someproject (unavailable)

**Comment by lyumengge** [comment]
![image](https://user-images.githubusercontent.com/80483932/110852611-8b3fb400-82ed-11eb-9c07-09d147ec8442.png)
