### ISSUE TITLE
Error Handling Modifications not in UniMod

### ISSUE THREAD

**Issue by xLinkKnight** [grosenberger/easypqp#55]
Usage situation:
Attempting to use EasyPQP during data processing with Fragpipe/MSFragger. Added variable modification within the search which would correspond to specific crosslinks of interest (not present in UniMod). The database search would complete without error but the subsequent SL step would fail.

Testing showed that the ```unimod``` file within ```\pyopenms\share\OpenMS\CHEMISTRY``` and possibly ```\easypqp\data``` had to contain the mass descriptor of the crosslink.

Is there a way to enter a variable modification within the MSFragger GUI and have it carryover to EasyPQP without the need to edit xml files? It's not difficult to add these entries to the unimod files. I'm just wondering if there is a command line argument I'm missing which would help the situation.

**Comment by grosenberger** [comment]
Did you try to use ``easypqp convert --enable_unannotated`` already? This will propagate unmatched delta masses and should also work with crosslinks.

**Comment by xLinkKnight** [comment]
I noticed that the the log file and cmd list both had the ```--enable_unannotated``` option set. I've attached the processing log file and cmd list.

[log_2021-04-03_17-33-57.txt](https://github.com/grosenberger/easypqp/files/6259435/log_2021-04-03_17-33-57.txt)
[cmds.txt](https://github.com/grosenberger/easypqp/files/6259436/cmds.txt)

Not sure what else I might be doing wrong.

**Comment by grosenberger** [comment]
Which version of EasyPQP are you using? Can you make sure that you are using the latest version 0.1.11? Some bugs were fixed that might have an effect on certain modification types.

**Comment by xLinkKnight** [comment]
FragPipe reports 0.1.11 and running ```easypqp --version``` returns 0.1.11.

**Comment by grosenberger** [comment]
Did EasyPQP actually generate the spectral library or did it fail somewhere? The log indicates that it worked, right? Could you please provide a minimum example of input data and used commands so I can reproduce the issue?

**Comment by xLinkKnight** [comment]
EasyPQP did generate the spectral library.

I wasn't able to recreate the issues by performing the search with the original unimod files. I'm not sure what the cause might have been, but it seems to be functioning as intended. The library now shows the the unannotated mass addition from the user suppled variable modification.

Think this issue has resolved itself. Sorry for taking up your time.

**Comment by grosenberger** [comment]
Great to hear that it now seems to work. 👍
