### ISSUE TITLE
Not sure which files to use.

### ISSUE THREAD

**Issue by PatrickvanZalm** [grosenberger/easypqp#71]
Hello,

Im trying to use CommandLine easypqp to create a spectral library from msfragger output. I cant seem to figure out which files to specify too.

My msfragger has the following structure:
```

msfraggeroutput
|    -sample1
|      -sample1_quant.csv
|       -sample1.pepXML
|       -sample1.pep.xml
|       -sample1_ion.tsv
|       -sample1_peptide.tsv
|       -sample1_protein.fas
|       -sample1_protein.tsv
|       -sample1_psm.tsv
|   -sample2
|       -sample2_quant.csv
|       -sample2.pepXML
|       -sample2.pep.xml
|       -sample2_ion.tsv
|       -sample2_peptide.tsv
|       -sample2_protein.fas
|       -sample2_protein.tsv
|       -sample2_psm.tsv
|    -MSstats.csv
|    -combined.pep.xml
|    -combined.prot.xml
|    -combined_peptide.csv
|    -combined_protein.tsv
|    -mbr_ion.tsv
|    -reprint.int.tsv
|    -reprint.spc.tsv

```
Should I just specify to the pepxml of each sample?
And what about the require spectra path? Im using Timstof files but we did not change them to mzXML or mgf format.

Best,
Patrick

**Comment by grosenberger** [comment]
Hi Patrick,

You need to use pepXML, ideally the ``combined.pep.xml`` file, as well as separate MGF or mzXML files. Unfortunately, EasyPQP does not yet directly support the vendor formats. If you ran MSFragger with built-in calibration and stored the output in MGF files, you could probably also use those.

Best regards,
George

**Comment by PatrickvanZalm** [comment]
Thank you George,

I will try to use the calibrated MGF files. Thanks for clarifying 👍 

Best,
Patrick

**Comment by PatrickvanZalm** [comment]
Hi George,

Its been a while but ive been trying to pick up this project again. In short; we have too much data to run this in normal Fragpipe software.

Im trying to use your tool; I have the combined.pep.xml file, as well as (un)calibrated .mgf for each timstof file. when I use the --help for the covert or library options of your tool, I do not really seem to find the place to use such files. Am I missing something here?

Best,
Patrick
