### ISSUE TITLE
Building library from independent FragPipe output

### ISSUE THREAD

**Issue by plbaldoni** [grosenberger/easypqp#74]
Hi there,

Is it possible to generate a single spectral library with easypqp from two (or, potentially more) independent MSFragger output?

For example, if I have two experiments, one digested with LysC and one digested with Trp, and run MSFragger independently on both datasets, can I somehow have a single spectral library for both?

Initially, I could generate the two libraries separately. But I want to avoid the issue of aligning RT and IM after the fact.

Thanks!

**Comment by fcyu** [comment]
I haven't tested it, but I think you can try the following. 

1. Use FragPipe to perform two sets of MSFragger searches and PSM validations (using PeptideProphet or Percolator). 
2. Move the these two sets of files to two folders located in the same big folder. The folder names are the experiment names.
3. Start a new FragPipe, load all mzML/raw files, and assign then into two experiments with the folders' names.
4. Load speclib workflow but uncheck MSFragger and PSM validation.
5. Run.

Please feel free to let me know if this approach works.

Best,

Fengchao

**Comment by plbaldoni** [comment]
Thanks Fengchao, I will try. For the files that are common between experiments (and used as input in easypqp), such as `psm.tsv` and `peptide.tsv`, should they be combined?

**Comment by fcyu** [comment]
You should only run MSFragger and PSM validation in the first step, so there will be no tsv files. In the fourth step, Philosopher will combine all runs' files, perform FDR filtering, and reporting.

Best,

Fengchao

**Comment by plbaldoni** [comment]
Thanks, Fengchao. That worked.
