### ISSUE TITLE
Controlling the number of threads for parsing

### ISSUE THREAD

**Issue by guoci** [grosenberger/easypqp#76]
In the `convert` command, the parsing of files with `OpenMS` is multithreaded, is there a way to control the number of threads for parsing?
Nesvilab/FragPipe#567

**Comment by grosenberger** [comment]
It seems that this will be an upcoming feature of pyOpenMS: https://github.com/OpenMS/OpenMS/pull/5839

We should definitely add support to control the number of threads as soon as this is available.

**Comment by guoci** [comment]
The environment variable `OMP_THREAD_LIMIT` can be used to limit the number of threads for now.

**Comment by fcyu** [comment]
`OMP_THREAD_LIMIT` does not work in Windows. Should set `OMP_NUM_THREADS`.

Best,

Fengchao
