### ISSUE TITLE
Documentation for integration with TPP

### ISSUE THREAD

**Issue by andrewrobertjones** [grosenberger/easypqp#83]
Hi,
I would like to use easypqp, following searches with Comet, then PeptideProphet, via TPP. Can you provide pointers to any documentation for necessary files at each step. I can convert pepXML files to psmpkl and peakpkl files, but I don't understand what role these files play in creating a library. The next step of the documentation talks about loading tsv files from Philosopher. Can EasyPQP work directly from the outputs of TPP?
thanks
Andy

**Comment by grosenberger** [comment]
Hi Andy,

yes, that should be possible, however I have not used this mode in a long time, so there might be some issues. You can just run ``easypqp library`` by providing the psmpkl and peakpkl files. The FDR cutoffs will then be computed by EasyPQP directly.

Best regards,
George
