### ISSUE TITLE
Why to exclude massdiff when convering pepXML

### ISSUE THREAD

**Issue by shubham1637** [grosenberger/easypqp#86]
Hi, 
   What is the reason behind having `exclude-range` parameter in `easypqp convert`? I have done database search with including deamidation modification, if the massdiff between [-1.5, 3.5] is not necessary, I well then remove it from the database search also. However, what is the rationale for not mapping them to UniMod?

**Comment by grosenberger** [comment]
Sometimes the peak-picking algorithms are confused and select the peaks of the wrong isotopes as the main precursor signal. This can be a challenge for open modification searching algorithms and particularly for the downstream automated UniMod mapping. For some analyses, however, the exclusion range can be omitted.
