### ISSUE TITLE
easypqp filter-unimod UnicodeDecodeError

### ISSUE THREAD

**Issue by karlssoc** [grosenberger/easypqp#89]
Hi,

I was trying to filter the unimod xml using the command below:

<pre><code>
easypqp filter-unimod --out unimod_ids.xml --ids [1,2,4,5,7,21,26,27,28,34,35,36,40,43,121,122,137,142,259,267,299,305,307,354,621,632,1409,1506,1531,1768]
</code></pre>

But I got a UnicodeDecodeError (see below) and no xml file was written.

I use ubuntu, python 3.9.0 & easypqp 0.1.30. I tried earlier versions of python, but with the same error. I aslo tried the docker container (grosenberger/easypqp:latest), but it lacked the filter-unimod option.

thanks,
Christofer

<pre><code>
INFO: Loading XML data from /data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/easypqp/data/unimod.xml
INFO: Appending to filtered unimod XML - title=Acetyl with record_id=1
INFO: Appending to filtered unimod XML - title=Amidated with record_id=2
INFO: Appending to filtered unimod XML - title=Carbamidomethyl with record_id=4
INFO: Appending to filtered unimod XML - title=Carbamyl with record_id=5
INFO: Appending to filtered unimod XML - title=Deamidated with record_id=7
INFO: Appending to filtered unimod XML - title=Phospho with record_id=21
INFO: Appending to filtered unimod XML - title=Pyro-carbamidomethyl with record_id=26
INFO: Appending to filtered unimod XML - title=Glu->pyro-Glu with record_id=27
INFO: Appending to filtered unimod XML - title=Gln->pyro-Glu with record_id=28
INFO: Appending to filtered unimod XML - title=Methyl with record_id=34
INFO: Appending to filtered unimod XML - title=Oxidation with record_id=35
INFO: Appending to filtered unimod XML - title=Dimethyl with record_id=36
INFO: Appending to filtered unimod XML - title=Sulfo with record_id=40
INFO: Appending to filtered unimod XML - title=HexNAc with record_id=43
INFO: Appending to filtered unimod XML - title=GG with record_id=121
INFO: Appending to filtered unimod XML - title=Formyl with record_id=122
INFO: Appending to filtered unimod XML - title=Hex(5)HexNAc(2) with record_id=137
INFO: Appending to filtered unimod XML - title=HexNAc(1)dHex(1) with record_id=142
INFO: Appending to filtered unimod XML - title=Label:13C(6)15N(2) with record_id=259
INFO: Appending to filtered unimod XML - title=Label:13C(6)15N(4) with record_id=267
INFO: Appending to filtered unimod XML - title=Carboxy with record_id=299
INFO: Appending to filtered unimod XML - title=dHex(1)Hex(3)HexNAc(4) with record_id=305
INFO: Appending to filtered unimod XML - title=dHex(1)Hex(4)HexNAc(4) with record_id=307
INFO: Appending to filtered unimod XML - title=Nitro with record_id=354
INFO: Appending to filtered unimod XML - title=Asn->Asp with record_id=621
INFO: Appending to filtered unimod XML - title=Gln->Glu with record_id=632
INFO: Appending to filtered unimod XML - title=Hex(5)HexNAc(4)NeuAc(1) with record_id=1409
INFO: Appending to filtered unimod XML - title=dHex(1)Hex(4)HexNAc(3)NeuGc(1) with record_id=1506
INFO: Appending to filtered unimod XML - title=Hex(9)HexNAc(2) with record_id=1531
INFO: Appending to filtered unimod XML - title=dHex(1)Hex(3)HexNAc(3) with record_id=1768
INFO: Writing out filtered unimod XML file to unimod_ids.xml
Traceback (most recent call last):
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/bin/easypqp", line 8, in <module>
    sys.exit(cli())
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/click/core.py", line 1690, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/easypqp/main.py", line 185, in filter_unimod
    unimod_filter(infile, outfile, accession_ids)
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/site-packages/easypqp/unimoddb.py", line 55, in unimod_filter
    lines = file_handle.readlines()
  File "/data/karlssoc/bin/miniconda3/envs/easypqp/lib/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3119: ordinal not in range(128)
</code></pre>

**Comment by singjc** [comment]
Hi Christofer,

Thank you for submitting this issue, I have fixed the issue, and submitted a PR. In the meantime, you can use the following docker image, [singjust/easypqp:0.1.31](https://hub.docker.com/layers/singjust/easypqp/0.1.31/images/sha256-870093a88245eea2a902a7eb34bc384baefdcf52ad2f10e39aab3a650174a992?context=repo) with the fix.

I have slightly changed the command, and added additional support for further restriction for specificity for specific residues, but you can run your previous restriction as follows:

```
docker run -it --rm -v $PWD:/data/ singjust/easypqp:0.1.31 easypqp filter-unimod --out /data/unimod_ids.xml --ids '1,2,4,5,7,21,26,27,28,34,35,36,40,43,121,122,137,142,259,267,299,305,307,354,621,632,1409,1506,1531,1768'
```

Best,

Justin
